### ISSUE TITLE
TypeError: request.getSession()

### ISSUE THREAD

**Issue by schwamic** [fastify/fastify-websocket#169]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.24.0

### Plugin version

4.0.0

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.1

### Description

Hi, 
I have tried to implement an asynchronous task in a wsHandler as described in the documentation. However, I get a TypeError as soon as I call `request.getSession()`. Either I have misunderstood something or the method is no longer available in the current version?

```js
const { QueryService } = require('@lib/infrastructure/database')
const enums = require('@lib/common/enums')

module.exports = function (fastify) {
  return {
    global: function (connection, request) {
      const sessionPromise = request.getSession() // <-- TYPE_ERROR

      connection.socket.on('close', async function (message) {
        await sessionPromise()
        const queryService = new QueryService()
        const client = await fastify.pg.connect()
        await client.query(queryService.players.updateState, [enums.playerStates.offline, request.query.playerId, request.query.gameId])
        fastify.websocketServer.clients.forEach(function (client) {
          if (client.readyState === 1) {
            client.send(JSON.stringify({ ...request.query, type: 'close' }))
          }
        })
      })
    }
  }
}
```
Reference: [Repository](https://github.com/schwamic/risiko/tree/main/packages/server/routes/subscriptions)

### Steps to Reproduce

Use `request.getSession()`

### Expected Behavior

No Error.

**Comment by airhorns** [comment]
Can you post the error that you get and see if you can create a minimal reproduction? It's hard and insecure for us to debug running a large codebase of someone elses, the closer you can get to the problem the more we can get!

**Comment by schwamic** [comment]
> Can you post the error that you get
```bash
{"level":50,"time":1639334951150,"pid":12450,"hostname":"schwamic.local","reqId":"req-i","stack":"TypeError: request.getSession is not a function\n    at Object.global (/Users/schwamic/Documents/risiko/packages/server/routes/subscriptions/subscriptions.controller.js:7:38)\n    at /Users/schwamic/Documents/risiko/node_modules/fastify-websocket/index.js:117:34\n    at /Users/schwamic/Documents/risiko/node_modules/fastify-websocket/index.js:67:7\n    at WebSocketServer.completeUpgrade (/Users/schwamic/Documents/risiko/node_modules/ws/lib/websocket-server.js:408:5)\n    at WebSocketServer.handleUpgrade (/Users/schwamic/Documents/risiko/node_modules/ws/lib/websocket-server.js:316:10)\n    at handleUpgrade (/Users/schwamic/Documents/risiko/node_modules/fastify-websocket/index.js:55:9)\n    at Object.routeOptions.handler (/Users/schwamic/Documents/risiko/node_modules/fastify-websocket/index.js:113:9)\n    at preHandlerCallback (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/handleRequest.js:109:5)\n    at handler (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/handleRequest.js:72:7)\n    at handleRequest (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/handleRequest.js:20:5)\n    at next (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/route.js:448:7)\n    at Object.preParsing (/Users/schwamic/Documents/risiko/node_modules/fastify-compress/index.js:299:14)\n    at next (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/route.js:458:18)\n    at preParsingHookRunner (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/route.js:478:3)\n    at runPreParsing (/Users/schwamic/Documents/risiko/node_modules/fastify/lib/route.js:425:5)","type":"Error","msg":"request.getSession is not a function"}
```

> and see if you can create a minimal reproduction?

si klaro! https://github.com/schwamic/issues-169

Thank you for your help!

**Comment by mcollina** [comment]
It seems you are not defining getSession() anywhere. Check out fastify-secure-session or fastify-session.

**Comment by schwamic** [comment]
I think this should definitely be included in the README. How is anyone supposed to know where `getSession` comes from? I thought it was part of fastify. I can take over and set a PR if that helps you?

**Comment by mcollina** [comment]
Go for it, thanks!
