### ISSUE TITLE
TypeError: connection.socket.send is not a function

### ISSUE THREAD

**Issue by akvlad** [fastify/fastify-websocket#218]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

According to the readme https://github.com/fastify/fastify-websocket/blob/master/README.md?plain=1#L39 I use `connection.socket.send` to send a message to the client.
It worked for `"fastify-websocket": "^4.0.0",`. 
Now I have the error:
```
/home/123/qryn/lib/handlers/tail.js:8
      connection.socket.send(s)
                            ^

TypeError: connection.socket.send is not a function
    at Watcher.onData (/home/123//qryn/lib/handlers/tail.js:8:29)
    at Watcher.emit (node:events:527:28)
    at Watcher.flush (/home/123/qryn/lib/db/watcher.js:117:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

Process finished with exit code 1
```
In your latest tests I see `connection.write`: https://github.com/fastify/fastify-websocket/blob/master/test/base.js#L31
What is the correct method to send a message to the client?

**Comment by akvlad** [comment]
Well, apparently it needed an extra
```
fastify.register(async function (fastify) {
``` 
as it was mentioned in the readme. Sorry for interruption.
