### ISSUE TITLE
noServer option has no effect

### ISSUE THREAD

**Issue by MoJo2600** [fastify/fastify-websocket#88]
## 🐛 Bug Report

The setting `noServer = true` in options has no effect. I was trying to implement a websocket authorization, based on the examples provided in the ws repository. To handle the upgrade of the connection, the setting `noServer` must be set to `true`. If i do so in fastify-websocket, this has no effect.

The issue is, that ws checks for the setting, but this is overruled by a check of the property `server` of the ws instance. This property is always set in fastify-websocket regardless of the `noServer` setting.

See ws/lib/websocket-server.js Line 81
```js
{
   ... check for parmeter noServer
} else if (options.server) {
   this._server = options.server;
}

if (this._server) {
   ...
```
This leads to the following error in my case:

```
Error: server.handleUpgrade() was called more than once with the same socket, possibly due to a misconfiguration
    at WebSocketServer.completeUpgrade (/workspace/backend/node_modules/ws/lib/websocket-server.js:267:13)
    at WebSocketServer.handleUpgrade (/workspace/backend/node_modules/ws/lib/websocket-server.js:245:10)
    at Server.<anonymous> (/workspace/backend/src/index.ts:197:28)
    at Server.emit (events.js:326:22)
    at Server.EventEmitter.emit (domain.js:486:12)
    at onParserExecuteCommon (_http_server.js:644:14)
    at onParserExecute (_http_server.js:577:3)
    at HTTPParser.callbackTrampoline (internal/async_hooks.js:129:14) uncaughtException
```

## To Reproduce

Set the parameter noServer to true

```js
// Paste your code here
```

## Expected behavior

The server property of ws should only be set when `noServer` is null or false.

```js
// Paste the expected results here
```

## Your Environment

- *node version*: 14
- *fastify version*: >=2.0.0
- *os*: Linux

**Comment by MoJo2600** [comment]
Maybe i should point out, why I use the `noServer` property after all. The [websocket documentation](https://github.com/websockets/ws/blob/7d39f19ee2b87e5c4eaec34c13a88de651533bdc/doc/ws.md) states:

> **NOTE:** Use of `verifyClient` is discouraged. Rather handle client
> authentication in the `upgrade` event of the HTTP server. See examples for
> more details.

The example implementation uses the `noServer` option to handle the upgrade event. This is what I'm doing, but what is not working because of the always set `server` property.
